# Generated by Django 5.2.7 on 2025-12-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('departure_station', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('arrival_station', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
