# Generated by Django 5.2.7 on 2025-12-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrainBooking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainTimes',
            new_name='TrainTime',
        ),
    ]
